name: build gdal python image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/gdal-python-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set image tag as current date
      run: echo "IMAGE_TAG=$(date +%Y%m%d)" >> "$GITHUB_ENV"

    - name: Build and push gdal_python image from base
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWD: ${{ secrets.DOCKER_HUB_PASSWD }}
      run: |
        docker login registry-1.docker.io -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWD
        cat > Dockerfile.gdal_python <<EOF
        FROM flyisnow/gdal:3.10.3-compress
        
        RUN apt-get update && apt-get install -y --no-install-recommends \
          graphviz \
          gv \
          python3-pandas \
          python3-scipy \
          python3-netcdf4 \
          python3-xarray \
          && apt-get clean \
          && rm -rf /var/lib/apt/lists/* /usr/share/doc/* /usr/share/man/* /usr/share/locale/*
        EOF

        docker build . --file Dockerfile.gdal_python --tag registry-1.docker.io/flyisnow/gdal_python:3.10.3_$IMAGE_TAG
        docker run --rm registry-1.docker.io/flyisnow/gdal_python:3.10.3_$IMAGE_TAG bash -lc 'java -version 2>&1 | grep "1.8.0"'
        docker push registry-1.docker.io/flyisnow/gdal_python:3.10.3_$IMAGE_TAG

    - name: Cleanup temp Dockerfile
      if: always()
      run: rm -f Dockerfile.gdal_python