name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set image tag as current date
      run: echo "IMAGE_TAG=$(date +%Y%m%d)" >> "$GITHUB_ENV"
    - name: Build the Docker image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWD: ${{ secrets.DOCKER_HUB_PASSWD }}
      run: |
        docker login registry-1.docker.io -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWD
        docker build . --file Dockerfile --tag registry-1.docker.io/flyisnow/gdal_debug:$IMAGE_TAG
        docker push registry-1.docker.io/flyisnow/gdal_debug:$IMAGE_TAG
        
