name: build gdal 3.10 Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/gdal-build.yml'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the gdal Docker image
      env:
        IMAGE_TAG: ${{ github.sha }} # 用于标记容器版本号
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWD: ${{ secrets.DOCKER_HUB_PASSWD }}
        
      run: |
        docker login registry-1.docker.io -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWD
        export TARGET_IMAGE=flyisnow/gdal
        mkdir OSGeo && cd OSGeo && git clone https://github.com/flyisnow/gdal -b release/3.10
        cd gdal/docker/ubuntu-full && ./build.sh --platform linux/amd64 --push --docker-repository registry-1.docker.io --tag ubuntu-full --gdal 3.10.3 --proj 9.3.1 --release --with-debug-symbols --no-rsync-daemon
        docker images
       
        
